### ISSUE TITLE
User guide instructions for plotting import error

### ISSUE THREAD

**Issue by schoeller** [Deltares/pyflwdir#13]
Dear all,

thanks for this package. I am running conda 4.11 on Win10 and have installed pyflwdir as [instructed](https://deltares.github.io/pyflwdir/latest/installation.html#install-from-conda). When following the user guide instructions for [plotting](https://deltares.github.io/pyflwdir/latest/flwdir.html#Flow-direction-data) I stumble upon below error.

```
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from utils import quickplot, colors, cm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'utils'
```

Any hints on how to alleviate the situation are highly welcome. Same counts for install under Ubuntu WSL. 

Kind regards

Sebastian

**Comment by DirkEilander** [comment]
Hi @schoeller. `utils` is not a submodule of pyflwdir but a simple script to make some plots in the examples. We currently do not have any plotting functionality within the package as this is covered by many other packages. If you'd like to use the utils.py functions you can find the file the notebooks folder: https://github.com/Deltares/pyflwdir/blob/main/notebooks/utils.py Your script should be able to find it if you place the utils.py file in the same folder as your script.
