### ISSUE TITLE
Failed read MERIT flowdir

### ISSUE THREAD

**Issue by lj512lj512** [Deltares/pyflwdir#14]
ValueError: The flow direction data with type "d8" is invalid.

**Comment by DirkEilander** [comment]
Hi @lj512lj512. I work without problems with the MERIT flow direction data. Could you provide a small reproducible script (perhaps with some sample data attached) that shows the error?

**Comment by lj512lj512** [comment]
> Hi @lj512lj512. I work without problems with the MERIT flow direction data. Could you provide a small reproducible script (perhaps with some sample data attached) that shows the error so that I can help you solve it?

Hi @DirkEilander , thank you very much. I did some operation of the MERIT flowdir data, then I got the error. I tried to download the data again and used it directly in pyflwdir, it worked.

**Comment by lj512lj512** [comment]
@DirkEilander 
While I have some new issues when using utils.py function, I cannot import the functions from utils package, it seems the utils package you use is different from what i installed by pip

**Comment by DirkEilander** [comment]
Glad you can work with the MERIT data. See more background on the utils.py script in #13
I'll add some comments in the examples to it more clear that this is a local script used for the examples only.
