### ISSUE TITLE
error in plotting the river mouths using the nextxy.bin dataset

### ISSUE THREAD

**Issue by Jiangchao3** [Deltares/pyflwdir#23]
Hi @DirkEilander ,

I want to identify all of the river mouth and make a plot using the 3 arcmin river network dataset nextxy.bin.

But it is odd that the figure I plotted here seems reversed in the latitude. Could you please have a look? Many thanks.

Best regards,
Jiangchao

**my scripts:**

import pyflwdir
import numpy as np

bbox=[-180, -90, 180, 90]
data, transform = pyflwdir.read_nextxy(
    fn='glb_03min/nextxy.bin', nrow=3600, ncol=7200, bbox=bbox)

import xarray as xr
xr.DataArray(data[0]).plot()
![image](https://user-images.githubusercontent.com/66854878/156882489-8204d1e4-b09c-46e4-9e65-a8b79e00392c.png)

x = data[0]
lon = np.linspace(-180,180,7200)
lat = np.linspace(-90,90,3600)
lon[np.where(x==-9)[1]],lat[np.where(x==-9)[0]] 

import geopandas as gpd
from shapely.geometry import Point 
gdf = gpd.GeoDataFrame([Point(x, y) for x,y in zip(lon[np.where(x==-9)[1]], lat[np.where(x==-9)[0]])])
gdf.columns = ['geometry']

world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
fig, ax = plt.subplots()
gdf.plot(ax=ax,markersize=0.1, color='red')
world.plot(ax=ax);
![image](https://user-images.githubusercontent.com/66854878/156882494-53319f4d-3c9d-41ea-b57e-cb5c775a3770.png)

**Comment by DirkEilander** [comment]
Hi @Jiangchao3, I believe the nextxy data is orientated North -> South (the first row is the most northern), which you also see in the xarray plot. Xarray jus plots the first row in the bottom based on nc contentions which dictate that data is oriented South -> North. To get the correct point locations you need to also make you `lat` array from north to south `lat = np.linspace(90,-90,3600).` 

You can also parse the data with `flw = pyflwdir.from_array(data, ftype='nextxy', transform=transform)` and than use the `idxs = flw.idxs_pit` attribute in combination with the `x, y = flw.xy(idxs)` method to get the x, y location of outlets.

PS:  To get a correct xarray plot you need to add the correct lat and lon dimension coordinates.

**Comment by Jiangchao3** [comment]
Hi @DirkEilander ,

Thanks for your kindly reply. No error occured after using the `lat =np.linspace(90,-90,3600).`

And thanks for recommonding the `idxs = flw.idxs_pit` method. It works very well.
![image](https://user-images.githubusercontent.com/66854878/156919120-8cbebff2-97c9-4474-b908-5d1817cb9c73.png)
But it seems to find all the outlets (both -10 and -9), could I set a parameter to **only find the outlet (-10) or outlet (-9)**?
I have a try using the
 `idxs = flw.idxs_pit(-9)`  or
 `flw = pyflwdir.from_array(data,ftype='nextxy',idxs_pit='-9',latlon=True,transform = transform)`
but boht failed. 

Looking forward to your help!

Best,
Jiangchao

**Comment by DirkEilander** [comment]
Glad it works. We don't distinguish between different types of river outlets (-9) and inland pits (-10) in pyflwdir as most D8 flow direction types don't have this distinction. What you could do is after reading and parsing the nextxy data drop the locations corresponding to inland pits:

```
idxs = flw.idxs_pit
nextx = data[0]
idxs = idxs[nextx.flat[idxs] == -9]
x, y = flw.xy(idxs)
```

**Comment by Jiangchao3** [comment]
The script your put here can identify all the river mouth pits.

Many thanks for your help!

**Comment by Jiangchao3** [comment]
Dear @DirkEilander,  I am trying to get discharge timeseries from the CaMa-flood output data according to the (x,y) coordinate of the river outlets(-9).

I am not sure the rivermouth points obtained by x, y = flw.xy(idxs) is the center of each pits?

The following screensnaps shows the information of my CaMa-flood output discharge.

![image](https://user-images.githubusercontent.com/66854878/169286534-5255ae0d-0130-4f07-b8f6-8d14c6bfc6b7.png)

Could you please give me some suggestions on how to get discharges of each rivermouts pits?

Many thanks!

Jiangchao

**Comment by DirkEilander** [comment]
> I am not sure the rivermouth points obtained by x, y = flw.xy(idxs) is located at the center of each pits?

The coordinates obtained with that function should be at the center of the cell if the transform is set well when initializing flw.

**Comment by Jiangchao3** [comment]
> The coordinates obtained with that function should be at the center of the cell if the transform is set well when initializing flw.

Got it. Thanks for your relply.
