### ISSUE TITLE
No implementation of function Function(<built-in function heappush>) found for signature

### ISSUE THREAD

**Issue by akkana** [Deltares/pyflwdir#39]
I'm trying to get started with pyflwdir -- it looks very powerful. But the code in the quickstart at https://deltares.github.io/pyflwdir/latest/quickstart.html fails when executed in a newly created Python 3.11.6 virtualenv (on Linux, Debian sid, if that matters) after pip installing pyflwdir and rasterio:
 (and sorry for the formatting -- I'm using "code <>" but github's markdown seems to be treating python interpreter output like an email message instead of code):

`
>>> import rasterio
>>> with rasterio.open("n35_w107_1arc_v3.tif", "r") as src:
...     elevtn = src.read(1)
...     nodata = src.nodata
...     transform = src.transform
...     crs = src.crs
... 
>>> import pyflwdir
>>> flw = pyflwdir.from_dem(
...     data=elevtn,
...     nodata=src.nodata,
...     transform=transform,
...     latlon=crs.is_geographic,
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/akkana/Data/demnames/dem-full-env/lib/python3.11/site-packages/pyflwdir/pyflwdir.py", line 97, in from_dem
    d8 = dem.fill_depressions(
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akkana/Data/demnames/dem-full-env/lib/python3.11/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/akkana/Data/demnames/dem-full-env/lib/python3.11/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function heappush>) found for signature:
 
 >>> heappush(list(Tuple(int16, uint8, uint32, uint32))<iv=None>, Tuple(int64, uint8, uint32, uint32))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'heappush': File: numba/cpython/heapq.py: Line 150.
    With argument(s): '(list(Tuple(int16, uint8, uint32, uint32))<iv=None>, Tuple(int64, uint8, uint32, uint32))':
   Rejected as the implementation raised a specific error:
     TypingError: heap type must be the same as item type
  raised from /home/akkana/Data/demnames/dem-full-env/lib/python3.11/site-packages/numba/cpython/heapq.py:119

During: resolving callee type: Function(<built-in function heappush>)
During: typing of call at /home/akkana/Data/demnames/dem-full-env/lib/python3.11/site-packages/pyflwdir/dem.py (130)

File "dem-full-env/lib/python3.11/site-packages/pyflwdir/dem.py", line 130:
def fill_depressions(
    <source elided>
            if ~queued[r, c]:  # add to queue
                heapq.heappush(q, (z1, np.uint8(0), np.uint32(r), np.uint32(c)))
                ^
`

This error was mentioned in Issue #10 and there was a request to try a more recent numba, but that was in 2021 and I see this with the numba currently in pip.

The elevation data I'm using is SRTM downloaded four years ago -- maybe there's a newer format that pyflwdir is expecting?

**Comment by akkana** [comment]
I haven't yet found a working source for newer SRTM data, but I tried it with Copernicus data from https://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/elevation/copernicus-dem/elevation (10_DEM_y30x-110.tif) and got the same error.

**Comment by mgf-unige** [comment]
I get the same error using NASADEM data (https://www.earthdata.nasa.gov/esds/competitive-programs/measures/nasadem).

**Comment by mgf-unige** [comment]
Maybe it's caused by DEMs that are of type Integer. I tried with a DEM in Float32 that worked, then after conversion into Int16 it failed with this error. I say maybe because as the data is altered, maybe there are also artifacts created during the conversion that cause the issue.

**Comment by DirkEilander** [comment]
Thanks for posting the issue and a workaround. 

It seems `z1` in the line below somehow (not sure why) is of a different dtype than the elevation grid causing the issue. Forced it to be the same dtype will probably solve it. https://github.com/Deltares/pyflwdir/blob/3dd0e04d6cd53aea1d692b0052a83df784a18f6b/pyflwdir/dem.py#L130

**Comment by DirkEilander** [comment]
This should be fixed in PR #41 and will be added to the next release. For now you can install the latest development version from the main branch of the github repos. Feel free to reopen in case the issue is not solved.
