### ISSUE TITLE
TypeError when use from_dem to get FlowDirRaster

### ISSUE THREAD

**Issue by forestbat** [Deltares/pyflwdir#52]
### pyFlwDir version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of pyFlwDir.

### Reproducible Example

```
import pyflwdir
import rasterio
with rasterio.open(src_dem, "r") as src:
    elevtn = src.read()
    nodata = src.nodata
    transform = src.transform
    latlon = src.crs.is_geographic
    crs = src.crs
flw = pyflwdir.from_dem(
    data=elevtn,
    nodata=src.nodata,
    transform=transform,
    latlon=latlon,
    outlets="min",
)
```
src_dem is uploaded here.
[biliu_river.zip](https://github.com/user-attachments/files/16668414/biliu_river.zip)

### Current behaviour

`TypeError: cannot store {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]} to i1*: mismatching types`

### Desired behaviour

I want to get correct `FlowDirRaster` object like this article: https://deltares.github.io/pyflwdir/latest/_examples/from_dem.html

### Additional context

pyflwdir==0.5.8

**Comment by debpal** [comment]
Try this. Hope it will work.
with rasterio.open(src_dem, "r") as src:
    elevtn = src.read().astype('float32')

**Comment by forestbat** [comment]
> Try this. Hope it will work. with rasterio.open(src_dem, "r") as src: elevtn = src.read().astype('float32')

Thank for reply, but it doesn't work.
https://pastebin.com/XCCNUfXa

**Comment by debpal** [comment]
> > Try this. Hope it will work. with rasterio.open(src_dem, "r") as src: elevtn = src.read().astype('float32')
> 
> Thank for reply, but it doesn't work. https://pastebin.com/XCCNUfXa

Sorry to hear that it does not work. When I started with `pyflwdir`, it gave error because of integer data type of ratser. For float type, it worked well. That is why I gave you the solution. From the error, it seems that you are using miniconda and from the chatgpt, it is a LLVM (Low-Level Virtual Machine) error. I would recommend to install 'Anaconda', and then install `pyflwdir` in a separate environment. I hope it would work.

**Comment by forestbat** [comment]
> > > Try this. Hope it will work. with rasterio.open(src_dem, "r") as src: elevtn = src.read().astype('float32')
> > 
> > 
> > Thank for reply, but it doesn't work. https://pastebin.com/XCCNUfXa
> 
> Sorry to hear that it does not work. When I started with `pyflwdir`, it gave error because of integer data type of ratser. For float type, it worked well. That is why I gave you the solution. From the error, it seems that you are using miniconda and from the chatgpt, it is a LLVM (Low-Level Virtual Machine) error. I would recommend to install 'Anaconda', and then install `pyflwdir` in a separate environment. I hope it would work.

Now I solved the problem.
```
with rasterio.open(src_dem, "r") as src:
    elevtn = src.read(1)
    nodata = src.nodata
    transform = src.transform
    latlon = src.crs.is_geographic
    crs = src.crs
flw = pyflwdir.from_dem(
    data=elevtn,
    nodata=src.nodata,
    transform=transform,
    latlon=latlon,
    outlets="min",
)
```
