### ISSUE TITLE
Issues: from utils import vectorize

### ISSUE THREAD

**Issue by AquaPore** [Deltares/pyflwdir#53]
### pyFlwDir version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of pyFlwDir.

### Reproducible Example

A great thanks for deriving such an amazing tool to help to derive the data to feed into the WFLOW Julia model.

The PyFlwDir seem to be working well except fror:

`from utils import vectorize`

were *vectorize* is not being recognised.

And therefore I am not able to perform the simple task as in your example:

`gdf_bas = vectorize(subbasins.astype(np.int32), 0, flw.transform, name="basin")`

Will you kindly inform me if the following code which I derived from your excellent website works on your computer?

```
import geopandas as gpd
import numpy as np
import rasterio
import pyflwdir
from utils import vectorize

# define output locations
x, y = np.array([4.67916667, 7.60416667]), np.array([51.72083333, 50.3625])
gdf_out = gpd.GeoSeries(gpd.points_from_xy(x, y, crs=4326))
# delineate subbasins
subbasins = flw.basins(xy=(x, y), streams=flw.stream_order() >= 4)
# vectorize subbasins using the vectorize convenience method from utils.py
gdf_bas = vectorize(subbasins.astype(np.int32), 0, flw.transform, name="basin")
gdf_bas.head()
```

Many thanks for any help you may provide,
Joseph

### Current behaviour

_ImportError: cannot import name 'vectorize' from 'utils' (c:\Users\PollaccoJ\.julia\conda\3\x86_64\envs\hydromt-wflow\Lib\site-packages\utils\__init__.py)_

### Desired behaviour

Free from error

### Additional context

Please appologize for such a basic question, as I am somewhat new to spatial modelling. I am in the Southern hemisphere so there might be some extra complications.

My other questions is the coordinate system used to define the output location is the same as when for e.g. the coordinate (y,x) system as shown in QGIS . **it did not seem to work**.  Or do we need to perform transformation to the gridded coordinate system used by PyFlwDir?

Many thanks for any help you may provide,
Joseph

**Comment by DirkEilander** [comment]
Pyflwdir has a [FlwdirRaster.streams](https://deltares.github.io/pyflwdir/latest/_generated/pyflwdir.FlwdirRaster.streams.html) to vecotrize stream segments and [FlwdirRaster.vectorize](https://deltares.github.io/pyflwdir/latest/_generated/pyflwdir.FlwdirRaster.vectorize.html) to vectorize the raster a pixel level.

An example for the FlwdirRaster.streams method is also given in the [user guide examples](https://deltares.github.io/pyflwdir/latest/_examples/streams.html#Strahler-stream-order)
