### ISSUE TITLE
Helper function to get coordinates from linear indices

### ISSUE THREAD

**Issue by JasonDalton** [Deltares/pyflwdir#9]
Feature request:  This may be in the code but I haven't see it in the docs anywhere.  The flow path trace function returns a list of pixel indices in the linear index format.  A helper function to convert to the coordinate system of the raster would be helpful.

**Comment by DirkEilander** [comment]
Closing this issue with the comments above. @JasonDalton please reopen if the suggested methods do not work for your case.
